import os
from matplotlib.pyplot import imshow

import deephistopath.wsi.slide as slide
import deephistopath.wsi.util as util
import deephistopath.wsi.filter as filter
import deephistopath.wsi.tiles as tiles


def multiprocessing_pipeline(base_dir, turtle_files, tile_size=1024, zoom_level=0):
    """
    Call wsi-preprocessing multiprocess pipeline to work on specified folder

    Args:
        base_dir: directory containing wsi files
        turtle_files: this is the list of files generated by py_wsi turtle
        tile_size: size of tile / patch, assuming always square
        zoom_level: zoom level of tile / patch, 0 would be lowest zoom level (ie. largest zoom)
                    at zoom_level 2, details are usually barely visible
    """
    slide.BASE_DIR = base_dir

    slide.SRC_TRAIN_DIR = slide.BASE_DIR
    slide.DEST_TRAIN_DIR = os.path.join(
        slide.BASE_DIR, "training_" + slide.DEST_TRAIN_EXT)
    slide.DEST_TRAIN_THUMBNAIL_DIR = os.path.join(
        slide.BASE_DIR, "training_thumbnail_" + slide.THUMBNAIL_EXT)
    slide.FILTER_DIR = os.path.join(
        slide.BASE_DIR, "filter_" + slide.DEST_TRAIN_EXT)
    slide.FILTER_THUMBNAIL_DIR = os.path.join(
        slide.BASE_DIR, "filter_thumbnail_" + slide.THUMBNAIL_EXT)
    slide.TILE_SUMMARY_DIR = os.path.join(
        slide.BASE_DIR, "tile_summary_" + slide.DEST_TRAIN_EXT)
    slide.TILE_SUMMARY_ON_ORIGINAL_DIR = os.path.join(
        slide.BASE_DIR, "tile_summary_on_original_" + slide.DEST_TRAIN_EXT)
    slide.TILE_SUMMARY_THUMBNAIL_DIR = os.path.join(
        slide.BASE_DIR, "tile_summary_thumbnail_" + slide.THUMBNAIL_EXT)
    slide.TILE_SUMMARY_ON_ORIGINAL_THUMBNAIL_DIR = os.path.join(
        slide.BASE_DIR, "tile_summary_on_original_thumbnail_" + slide.THUMBNAIL_EXT)
    slide.TILE_SUMMARY_HTML_DIR = slide.BASE_DIR
    slide.TILE_DATA_DIR = os.path.join(slide.BASE_DIR, "tile_data")
    slide.TOP_TILES_DIR = os.path.join(
        slide.BASE_DIR,
        slide.TOP_TILES_SUFFIX +
        "_" +
        slide.DEST_TRAIN_EXT)
    slide.TOP_TILES_THUMBNAIL_DIR = os.path.join(
        slide.BASE_DIR,
        slide.TOP_TILES_SUFFIX +
        "_thumbnail_" +
        slide.THUMBNAIL_EXT)
    slide.TOP_TILES_ON_ORIGINAL_DIR = os.path.join(
        slide.BASE_DIR,
        slide.TOP_TILES_SUFFIX +
        "_on_original_" +
        slide.DEST_TRAIN_EXT)
    slide.TOP_TILES_ON_ORIGINAL_THUMBNAIL_DIR = os.path.join(
        slide.BASE_DIR,
        slide.TOP_TILES_SUFFIX +
        "_on_original_thumbnail_" +
        slide.THUMBNAIL_EXT)
    slide.TILE_DIR = os.path.join(
        slide.BASE_DIR,
        "tiles_" + slide.DEST_TRAIN_EXT)
    slide.STATS_DIR = os.path.join(slide.BASE_DIR, "svs_stats")

    slide.SLIDE_NAMES = turtle_files
    # slide.TRAIN_PREFIX = output_prefix

    tiles.ROW_TILE_SIZE = tile_size
    tiles.COL_TILE_SIZE = tile_size
    tiles.ZOOM_LEVEL = zoom_level

    print('================START================')
    slide.multiprocess_training_slides_to_images()
    print('=====================================')
    filter.multiprocess_apply_filters_to_images()
    print('=====================================')
    tiles.multiprocess_filtered_images_to_tiles()
    print('=================END=================')


def file_stats(file_dir, file_name):
    """
    Print Stats from openslide and py-wsi. Show scaled image at the end.

    Args:
        file_dir: The directory containing wsi files.
        file_name: The wsi file name.
    """
    # info 1
    print('Openslide info:\n')
    slide.single_slide_info(os.path.join(file_dir, file_name))
    print('\n\n\n')
    # show image
    pil_img, large_h, large_w, new_h, new_w = slide.show_scaled_slide_image(
        os.path.join(file_dir, file_name))
    imshow(pil_img)
